name: Rust Tests

on:
  push:
    branches: [ main, LandingPage, "feature/*", "bug/*" ]
    paths:
      - 'VCTCareerBackend/**'
      - '.github/workflows/rust-tests.yml'
  pull_request:
    branches: [ main, LandingPage ]
    paths:
      - 'VCTCareerBackend/**'
      - '.github/workflows/rust-tests.yml'

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db

jobs:
  test:
    name: Run Rust Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: VCTCareerBackend -> target

    - name: Check Rust formatting
      run: cargo fmt --check
      working-directory: VCTCareerBackend

    - name: Run Clippy lints
      run: cargo clippy --all-targets --all-features -- -D warnings
      working-directory: VCTCareerBackend

    - name: Run tests
      run: cargo test --verbose
      working-directory: VCTCareerBackend
      
    - name: Run tests with coverage
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --verbose --all-features --workspace --timeout 120
      working-directory: VCTCareerBackend

  build:
    name: Build Release
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: VCTCareerBackend -> target

    - name: Build release
      run: cargo build --release --verbose
      working-directory: VCTCareerBackend

    - name: Upload release binary
      uses: actions/upload-artifact@v4
      with:
        name: vctcareer-backend
        path: VCTCareerBackend/target/release/VCTCareerBackend
        retention-days: 7

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: VCTCareerBackend -> target

    - name: Security audit
      run: |
        cargo install cargo-audit
        cargo audit
      working-directory: VCTCareerBackend